[ci] troubleshooting release notes generation

diff --git a/ci/scripts/release b/ci/scripts/release
--- a/ci/scripts/release
+++ b/ci/scripts/release
@@ -115,5 +115,5 @@ EOS
 
 echo
 echo "--------------------------------------------------------------------------------"
-echo "SUCCESS"
-exit 0
+echo "FORCED FAILURE, NO SUCCESS"
+exit 1
