Moved/renamed dev/update tool
The dev/update tool was moved to the devtools directory and renamed with
a more descriptive name.  It also contains a check for the dependency of
cf-deployment repo in the same parent directory as this kit.

diff --git a/devtools/update-releases-from-cf-deployment b/devtools/update-releases-from-cf-deployment
--- a/devtools/update-releases-from-cf-deployment
+++ b/devtools/update-releases-from-cf-deployment
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+# Assumes you have cf-deployment repo checked out and located as a peer to this
+# repo
+if [[ -f ../cf-deployment/cf-deployment.yml ]] ; then
+  echo "Missing cf-deployment repo in parent directory"
+  exit 1
+fi
+
 upstream_releases=$(spruce json ../cf-deployment/cf-deployment.yml)
 releases=$(spruce json manifests/cf/releases.yml)
 buildpacks=$(spruce json manifests/cf/buildpacks.yml)
